language: ruby
rvm:
#  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode
#  - rbx-2.1.1
gemfile:
  - gemfiles/Gemfile.activerecord-2.3.x
  - gemfiles/Gemfile.activerecord-3.0.x
  - gemfiles/Gemfile.activerecord-3.1.x
  - gemfiles/Gemfile.activerecord-3.2.x
  - gemfiles/Gemfile.activerecord-4.0.x
matrix:
  exclude:
#    - rvm: 1.8.7
#      gemfile: gemfiles/Gemfile.activerecord-4.0.x
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.activerecord-4.0.x
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.activerecord-2.3.x
